---

- hosts: all
  become: true
  tasks:
    - name: Update cache 
      yum:
       update_cache: yes
         
    - name: Upgrade all packages on servers
      yum: 
        name: "*"
        state: latest