---
- hosts: webb
  tasks:
    - name: Install latest version of apache (httpd for centos)
      yum:
        name: httpd
        state: latest
    - name: Start apache at boot.
      service:
        name: httpd
        enabled: yes
        state: started
